{% set name = "azure-appconfiguration" %}
{% set version = "1.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cefd75b298b898a8ed9f73048f3f39f4e81059a58cd832d0523787fc1d912a06

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - azure-core >=1.30.0
    - isodate >=0.6.1
    - typing_extensions >=4.6.0

# Unable to run tests: No azure-devtools -> https://pypi.org/project/azure-devtools
test:
  imports:
    - azure.appconfiguration
    - azure.appconfiguration._generated
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/appconfiguration/azure-appconfiguration
  summary: Microsoft App Configuration Data Client Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Azure App Configuration is a managed service that helps developers centralize their application configurations simply and securely.
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/appconfiguration/azure-appconfiguration
  doc_url: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/appconfiguration/azure-appconfiguration/README.md
